### ISSUE TITLE
Add Dark Mode theme

### ISSUE THREAD

**Issue by coder2699** [coder2699/Dare2Change#11]
**Describe the feature you'd like**

1. Add dark mode theme. By default the app should work in the theme set on the system. Also, there should be an option given to the user to switch between Dark mode and Light mode themes.
2. Details on color schemes, etc  should be discussed before working on this feature

**Comment by PratyushSingh07** [comment]
Hey @coder2699 can I work on this issue ?

**Comment by coder2699** [comment]
@PratyushSingh07 consider taking up easier issues first

**Comment by PratyushSingh07** [comment]
@coder2699 I will work on other issues but the thing is I was playing around with the themes and this is what I have come up with 

[Screen Shot with Default System Theme ](https://drive.google.com/file/d/10RtWCmbUVcarp5D4BxxFsMt_gZXzvKs7/view?usp=sharing)

[Screen Shot with Dark Mode Enabled](https://drive.google.com/file/d/1zuY0NN36iuwri6TtxywsFdjIh3-qv8mA/view?usp=sharing)

[Screen Shot with Light Mode Enabled](https://drive.google.com/file/d/1mSUy19XzOL1vLT-HaL3C1eG_Jm8-Jlv8/view?usp=sharing)

I have used radio buttons similar to what we see on whatsapp when changing the theme

**Comment by coder2699** [comment]
ok you can take this up. But there will be lot of modifications required, specially regarding images, color themes etc. Please discuss over here in case of any doubts.

**Comment by PratyushSingh07** [comment]
Thank you for letting me try. So what modifications would you like regarding the images ,also where should I implement the radio buttons? In the home page ?

**Comment by coder2699** [comment]
> Thank you for letting me try. So what modifications would you like regarding the images ,also where should I implement the radio buttons? In the home page ?

Ideally, give a settings option in the toolbar (at homepage), like this:
![8QDxE](https://user-images.githubusercontent.com/61552810/194046722-b71c62b5-cfc7-4b07-ad26-075e50aec11a.png)

Regarding images, if you find anywhere any image without transparent background, causing a problem in dark mode, replace it with alternative image (please do mention such changes with screenshots)

**Comment by PratyushSingh07** [comment]
> > Thank you for letting me try. So what modifications would you like regarding the images ,also where should I implement the radio buttons? In the home page ?
> 
> Ideally, give a settings option in the toolbar (at homepage), like this: ![8QDxE](https://user-images.githubusercontent.com/61552810/194046722-b71c62b5-cfc7-4b07-ad26-075e50aec11a.png)
> 
> Regarding images, if you find anywhere any image without transparent background, causing a problem in dark mode, replace it with alternative image (please do mention such changes with screenshots)

ok, so once the user clicks on settings he will be given the choice to switch between light and dark mode?

**Comment by coder2699** [comment]
> > > Thank you for letting me try. So what modifications would you like regarding the images ,also where should I implement the radio buttons? In the home page ?
> > 
> > 
> > Ideally, give a settings option in the toolbar (at homepage), like this: ![8QDxE](https://user-images.githubusercontent.com/61552810/194046722-b71c62b5-cfc7-4b07-ad26-075e50aec11a.png)
> > Regarding images, if you find anywhere any image without transparent background, causing a problem in dark mode, replace it with alternative image (please do mention such changes with screenshots)
> 
> ok, so once the user clicks on settings he will be given the choice to switch between light and dark mode?

Yes, to choose between light, dark or system theme...and these settings should remain even when user closes and reopens the app.
