### ISSUE TITLE
Fix bug in "Focus Music" Screen

### ISSUE THREAD

**Issue by coder2699** [coder2699/Dare2Change#13]
**Describe the bug**
When Internet is not on, Music player doesn't work. It seems as if app has frozen. So, an appropriate message should be displayed.

**To Reproduce**
1. Turn OFF Internet
2. Open Music Player
3. Try to play music. Music doesn't play, it seems as if app is frozen

**Expected behavior**
Display a dialog box with a message " No Connection! try connecting to your Internet".

**Screenshots**
<img src="https://user-images.githubusercontent.com/61552810/179717173-aa1c4d28-24be-4529-9f00-d16ead9b11ea.jpg" width=240 height=480>

**Smartphone Info:**
|               | |
|---------------|-|
|Device         | Galaxy M51 |
|Android Version| 12 |

**Comment by PratyushSingh07** [comment]
I am unable to replicate this issue on my Samsung M11 however I have modified it so that the music doesn't play in absence of the internet. I will also make an appropriate toast in such a case. 

Having said that I would like to work on this issue @coder2699

**Comment by coder2699** [comment]
go ahead @PratyushSingh07
