### ISSUE TITLE
Add an option to reset tasks of all weekdays at once in "Weekly Planner"

### ISSUE THREAD

**Issue by coder2699** [coder2699/Dare2Change#14]
**Describe the feature**
Add an option in toolbar to reset tasks of all weekdays at once

**Current Screenshots**

<img src="https://user-images.githubusercontent.com/61552810/179720215-2fe096f5-73d4-4c4e-811e-e8dcbac2f485.jpg" width=240 height=480/>

**Comment by PratyushSingh07** [comment]
@coder2699 I would like to work on this issue

**Comment by coder2699** [comment]
@PratyushSingh07 go ahead

**Comment by coder2699** [comment]
@PratyushSingh07 go through the concept of "Android SQLite database migration"  before opening a PR
