### ISSUE TITLE
Fix typo error in "Success Mantras"

### ISSUE THREAD

**Issue by coder2699** [coder2699/Dare2Change#19]
**Describe the bug**

There's a typing error in the highlighted text view. 
Replace the highlighted textview by the following text - "Body and Mind are closely linked. When your body feels better so, too, will your mind."
<img src="https://user-images.githubusercontent.com/61552810/191840479-f61b8610-6900-45f2-9d6e-23bbb9290baa.jpeg" width=240 height=480>

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No

**Comment by PratyushSingh07** [comment]
Hey @coder2699  can i work on this issue ?

**Comment by coder2699** [comment]
@PratyushSingh07 go ahead

**Comment by coder2699** [comment]
give @PratyushSingh07 5 points
