### ISSUE TITLE
Fix the UI for horizontal layout of "Success Mantras" Screen 

### ISSUE THREAD

**Issue by coder2699** [coder2699/Dare2Change#9]
**Describe the bug**

In Success Mantras, when Tab of "How to Plan your day" is opened with horizontal orientation, the Images and Texts does not come properly. 

**To Reproduce**
1. Go to 'Success Mantras'
2. Rotate your phone to horizontal layout

**Screenshots**

![Screenshot_20220719-141750_Dare2Change](https://user-images.githubusercontent.com/61552810/179712526-751132e8-8c7b-4f14-bcc1-e31d18110285.jpg)

**Comment by PratyushSingh07** [comment]
@coder2699 i would like to work on this issue

**Comment by coder2699** [comment]
go ahead @PratyushSingh07

**Comment by PratyushSingh07** [comment]
Fixed #27
